### ISSUE TITLE
Centos data-binary needs to be fixed

### ISSUE THREAD

**Issue by remidinishanth-ntnx** [Jiab77/vuls-scripts#1]
There is some code to be fixed for centos, In this line https://github.com/Jiab77/vuls-scripts/blob/master/vuls-client-scan.sh#L61 it already contains data-binary and still, there is rpm query

![image](https://user-images.githubusercontent.com/53462873/87423554-231ebe00-c5f8-11ea-9dd7-fd9624116f0e.png)

I tried to fix in it PR and 
```bash
(base) base ❯     git push --set-upstream origin centos_fix
remote: Permission to Jiab77/vuls-scripts.git denied to remidinishanth.
fatal: unable to access 'https://github.com/Jiab77/vuls-scripts.git/': The requested URL returned error: 403
```

**Comment by Jiab77** [comment]
@remidinishanth My bad I see what you mean now 😅 I'll fix that today.
Thanks a lot for the reporting!

**Comment by Jiab77** [comment]
@remidinishanth I see that what you've spotted is also fixing this `curl` error:

```
curl: (3) Illegal characters found in URL
```

I'm gonna push the new file and close this issue after the commit. Thanks again for your reporting.

**Comment by Jiab77** [comment]
@remidinishanth I'm closing the issue now. Please feel free to create a new one if you spot something else 😉
